version: '3.9'

services:
  nginx:
    container_name: 'nginx-service'
    build: ./nginx
    ports:
      - 80:80
    depends_on:
      - clientsvc
  clientsvc:
    build: ./client-service
    deploy:
      replicas: 2
  usersvc:
    container_name: 'user-service'
    build: ./user-service
  emailsvc:
    container_name: 'email-service'
    build: ./email-service
