version: '3.9'

services:
  nginx:
    container_name: 'nginx-service'
    build: ./nginx
    ports:
      - 80:80
      - 90:90
    depends_on:
      - user
      - email
  user:
    container_name: 'user-service'
    build: ./user-service
  email:
    container_name: 'email-service'
    build: ./email-service
